### ISSUE TITLE
adapt code to RAD7

### ISSUE THREAD

**Issue by lrnzcig** [Iukekini/Baby-Monitor-Masimo-Pulse-Oximeter#1]
Hello,

Thank you very much for your project, it was really very useful for us (a friend of mine and myself). We are trying to setup a similar kind of monitor for my friend's daughter.

However, since we are using a Masimo RAD7 instead of RAD8, we had to adapt your code a bit. I'm referring to the [python script](https://github.com/Iukekini/Baby-Monitor-RAD8/blob/master/scripts/rad8monitor.py) for communicating with the device. I would like to commit our modifications so that they are available for anybody else, but of course I don't want to break your code. The modifications are mostly related to the way the line coming from the RS232 is parsed

There's several ways in which we could fix this, for example
- we do a fork and commit only into it, not into your project
- or I could refactor your code so that the connection part is separated from the parsing of the RS232 line. Then we can setup e.g. in the configuration file which kind of device we are using, and I would add an object for the device and 2 implementations for each of the models. I would put this into a pull request so that you can review it, comment, ask for modifications, etc

Maybe the second option is too much hassle for you, please let us know. Else, if you have other idea on how to do it, also let us know. If not, we can just do the fork and leave it there.

Anyway, thank you so much for posting your code!

**Comment by Iukekini** [comment]
I modified the code to separate the parsing from the reading and inserting into the database. You can add a RAD7 file in the devices folder.
