### ISSUE TITLE
authentication in the monitor

### ISSUE THREAD

**Issue by lrnzcig** [Iukekini/Baby-Monitor-Masimo-Pulse-Oximeter#3]
Hi!

I'm trying to use the monitor, but having problems with authentication, maybe you can give me a hint.... (By the way, I would not even need authentication, for the moment I'm just trying to set it up locally.)

I've setup the server with nodejs and I get into the initial screen "Login to access Kaleo Stats". If I create a new account, I get the message:

"Thank you for signing up for Kaleo Rocks but TJ needs to grant you access to this awesomeness first."

If I try to use OAuth with my Google account, well first of all the setup in my Google account is a bit weird, since I had to add "http://localhost:3000" to my Authorised Javascript origins, and "http://localhost:3000/auth/google/callback" to my Authorised Redirect URIs, but anyway Google did not seem to complain... when I use those credentials I seem to get through with OAuth, however in the callback I get the following error message:

Connect
500 InternalOAuthError: failed to fetch user profile
   at /Users/lrnzcig/git/Baby-Monitor-RAD8/app/node_modules/passport-google-oauth/lib/passport-google-oauth/oauth2.js:88:28
   at passBackControl (/Users/lrnzcig/git/Baby-Monitor-RAD8/app/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/Users/lrnzcig/git/Baby-Monitor-RAD8/app/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:91:20)
   at IncomingMessage.emit (events.js:185:7)
   at endReadableNT (_stream_readable.js:974:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)

Anyhow, besides this quick tests, what I would really like to know is your opinion on how to deal with authentication in a domain that is separate than yours, with my own user that it an admin, etc. I would appreciate any hint you can give.

Thanks!

**Comment by Iukekini** [comment]
For the quick and dirty

The permissions  are not fully functional right now. They just show or hide menu items. So if you go to "/admin" after you login you be able to modify your rights.

**Comment by Iukekini** [comment]
I added a settings file, in the config dir, that contains default new user permissions. This should allow you to all access by default if you need to.

**Comment by lrnzcig** [comment]
Both the quick and dirty and the settings file work perfectly fine. Thank you for your help!
